### ISSUE TITLE
Unable to authenticate/launch

### ISSUE THREAD

**Issue by nightah** [kodi-community-addons/plugin.audio.spotify#101]
Hardware: RPi2
OS: LibreELEC 8.2.5
Kodi: 17.3 Krypton
Addon Version: 1.1.58

After a fresh install of the addon when I have populated the username and password fields and the plugin attempts to run the following error is thrown:

```
20:47:59.759 T:1109390240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: (2, 'No such file or directory', '/storage/.kodi/userdata/addon_data/plugin.audio.spotify/credentials.json')
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.spotify/service.py", line 14, in <module>
                                                MainService()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 60, in __init__
                                                self.renew_token()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 167, in renew_token
                                                username = self.get_username()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 134, in get_username
                                                username = self.spotty.get_username()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 525, in get_username
                                                os.remove(cred_filename)
                                            OSError: (2, 'No such file or directory', '/storage/.kodi/userdata/addon_data/plugin.audio.spotify/credentials.json')
                                            -->End of Python script error report<--
```

I have checked and the `credentials.json` file does not appear to be generating in the location `/storage/.kodi/userdata/addon_data/plugin.audio.spotify/`.

A here's the error reproduced with debug logging turned on:

```
20:56:38.009 T:1650557856   DEBUG: Thread LanguageInvoker start, auto delete: false
20:56:38.010 T:1650557856    INFO: initializing python engine.
20:56:38.010 T:1650557856   DEBUG: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): start processing
20:56:38.011 T:1945657456   DEBUG: CAddonMgr: enabled plugin.audio.spotify
20:56:38.011 T:1609036704   DEBUG: Thread JobWorker start, auto delete: true
20:56:38.103 T:1650557856   DEBUG: -->Python Interpreter Initialized<--
20:56:38.103 T:1650557856   DEBUG: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): the source file to load is "/storage/.kodi/addons/plugin.audio.spotify/service.py"
20:56:38.110 T:1945657456   DEBUG: CGUIMediaWindow::GetDirectory (addons://recently_updated/)
20:56:38.111 T:1945657456   DEBUG:   ParentPath = [addons://recently_updated/]
20:56:38.111 T:1650557856   DEBUG: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): setting the Python path to /storage/.kodi/addons/plugin.audio.spotify:/storage/.kodi/addons/script.module.arrow/lib:/storage/.kodi/addons/script.module.beautifulsoup/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.cherrypy/lib:/storage/.kodi/addons/script.module.dateutil/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.metadatautils/lib:/storage/.kodi/addons/script.module.musicbrainz/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.simplecache/lib:/storage/.kodi/addons/script.module.simplejson/lib:/storage/.kodi/addons/script.module.six/lib:/storage/.kodi/addons/script.module.thetvdb/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
20:56:38.111 T:1650557856   DEBUG: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): entering source directory /storage/.kodi/addons/plugin.audio.spotify
20:56:38.112 T:1650557856   DEBUG: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): instantiating addon using automatically obtained id of "plugin.audio.spotify" dependent on version 2.1.0 of the xbmc.python api
20:56:38.615 T:1945657456   DEBUG: ------ Window Init (DialogBusy.xml) ------
20:56:38.659 T:1609036704   DEBUG: CAddonMgr::GetAvailableUpdates took 453 ms
20:56:38.814 T:1858073504   DEBUG: Thread BackgroundLoader start, auto delete: false
20:56:38.854 T:1858073504   DEBUG: Thread BackgroundLoader 1858073504 terminating
20:56:38.960 T:1945657456   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
20:56:41.315 T:1650557856   DEBUG: plugin.audio.spotify --> reported architecture: armv7l
20:56:41.827 T:1650557856   DEBUG: plugin.audio.spotify --> ok spotty v0.12.0
                                            {"debug":false,"lms-auth":true,"version":"0.12.0","volume-normalisation":true}
20:56:41.881 T:1650557856   DEBUG: plugin.audio.spotify --> Architecture detected. Using spotty binary /storage/.kodi/addons/plugin.audio.spotify/resources/lib/spotty/arm-linux/spotty-muslhf
20:56:42.275 T:1650557856   DEBUG: plugin.audio.spotify --> ok spotty v0.12.0
                                            {"debug":false,"lms-auth":true,"version":"0.12.0","volume-normalisation":true}
20:56:42.288 T:1650557856   DEBUG: plugin.audio.spotify --> started webproxy at port 52308
20:56:42.768 T:1650557856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: (2, 'No such file or directory', '/storage/.kodi/userdata/addon_data/plugin.audio.spotify/credentials.json')
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.spotify/service.py", line 14, in <module>
                                                MainService()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 60, in __init__
                                                self.renew_token()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 167, in renew_token
                                                username = self.get_username()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 134, in get_username
                                                username = self.spotty.get_username()
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 525, in get_username
                                                os.remove(cred_filename)
                                            OSError: (2, 'No such file or directory', '/storage/.kodi/userdata/addon_data/plugin.audio.spotify/credentials.json')
                                            -->End of Python script error report<--
20:56:42.772 T:1650557856    INFO: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): waiting on thread 1193702304
20:56:42.804 T:1945657456   DEBUG: ------ Window Init (DialogNotification.xml) ------
20:56:42.899 T:1650557856    INFO: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): waiting on thread 1160147872
20:56:42.999 T:1650557856    INFO: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): waiting on thread 1151759264
20:56:43.114 T:1650557856    INFO: CPythonInvoker(21, /storage/.kodi/addons/plugin.audio.spotify/service.py): waiting on thread 1118204832
```

**Comment by dkoukoul** [comment]
Thanks for that, I tried it on my Libreelec installation and unfortunately it fails.
The error is this:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Aborted
```
I would appreciate it if anyone has some feedback on this!
