### ISSUE TITLE
Tunnel connection failed: 404 Not Found

### ISSUE THREAD

**Issue by Silver-Volt4** [kodi-community-addons/plugin.audio.spotify#120]
Spotify worked earlier today, now it's throwing me this error:

2019-07-17 16:24:43.742 T:139987764877056   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ProxyError'>
                                            Error Contents: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/ (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 404 Not Found',)))
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.audio.spotify/service.py", line 14, in <module>
                                                MainService()
                                              File "/home/kodi/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 63, in __init__
                                                self.main_loop()
                                              File "/home/kodi/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 77, in main_loop
                                                self.switch_user(True)
                                              File "/home/kodi/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 129, in switch_user
                                                if self.renew_token():
                                              File "/home/kodi/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 179, in renew_token
                                                me = self.sp.me()
                                              File "/home/kodi/.kodi/addons/plugin.audio.spotify/resources/lib/spotipy/client.py", line 570, in me
                                                return self._get('me/')
                                              File "/home/kodi/.kodi/addons/plugin.audio.spotify/resources/lib/spotipy/client.py", line 148, in _get
                                                return self._internal_call('GET', url, payload, kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.audio.spotify/resources/lib/spotipy/client.py", line 110, in _internal_call
                                                r = self._session.request(method, url, headers=headers, proxies=self.proxies, **args)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 510, in send
                                                raise ProxyError(e, request=request)
                                            ProxyError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/ (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 404 Not Found',)))
                                            -->End of Python script error report<--

I'm using Linux.

**Comment by Kosmonafft** [comment]
I have the same issue

**Comment by silver-volt4** [comment]
Whoa, a two year old necrobump.

**Comment by Kosmonafft** [comment]
> Whoa, a two year old necrobump.

Maybe you remember if and how you solved that issue?
